"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Racine du projet (bon/) : contient backend/ et frontend/
PROJECT_ROOT = BASE_DIR.parent

# Charge les variables d'environnement depuis backend/.env (jamais commité)
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# En production (DEBUG=False), la SECRET_KEY est OBLIGATOIRE via l'environnement :
# Django lèvera une erreur si elle manque.
SECRET_KEY = os.environ.get('SECRET_KEY', 'dev-insecure-key-à-changer' if DEBUG else '')

ALLOWED_HOSTS = [h for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Applications tierces pour l'API REST
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',

    # Ton application
    'incidents',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Indispensable en toute première position
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Sert les fichiers statiques en production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Requis pour l'admin
    'django.contrib.messages.middleware.MessageMiddleware',        # Requis pour l'admin
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# En production : DATABASE_URL (ex. Neon postgres://user:pass@host/db)
if os.environ.get('DATABASE_URL'):
    DATABASES = {'default': dj_database_url.config(default=os.environ['DATABASE_URL'], conn_max_age=600)}
elif os.environ.get('DB_ENGINE', 'sqlite') == 'postgres':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'gestion_pannes_db'),
            'USER': os.environ.get('DB_USER', 'gestion_pannes_user'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Lubumbashi'

USE_I18N = True

USE_TZ = True


# Static files
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# En production, on sert aussi le frontend React déjà compilé (frontend/dist)
FRONTEND_DIST = PROJECT_ROOT / 'frontend' / 'dist'
STATICFILES_DIRS = [FRONTEND_DIST] if FRONTEND_DIST.exists() else []
WHITENOISE_ROOT = str(FRONTEND_DIST) if FRONTEND_DIST.exists() else None

AUTH_USER_MODEL = 'incidents.Utilisateur'

# Email
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Autoriser le frontend React (CORS)
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:5173,http://127.0.0.1:5173').split(',') if o.strip()
]

# Origines de confiance pour les formulaires (admin Django) derrière un proxy HTTPS
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]

# Configuration Django REST Framework & JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'incidents.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 20,
}

# Durées des tokens JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
}