# Generated by Django 6.1 on 2026-08-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='specialite',
            field=models.CharField(blank=True, choices=[('RESEAU', 'Réseau'), ('MATERIEL', 'Matériel'), ('LOGICIEL', 'Logiciel'), ('SECURITE', 'Sécurité'), ('IMPRESSION', 'Impression'), ('AUTRE', 'Autre')], max_length=30),
        ),
    ]
