# Generated by Django 6.1 on 2026-08-19 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_utilisateur_specialite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panne',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pannes', to='incidents.site'),
        ),
    ]
