# Generated by Django 6.1 on 2026-08-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_alter_panne_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
